In [2]:
import numpy as np, cv2

In [3]:
m = np.random.randint(0,100, 15).reshape(3,5)           # 임의 난수 생성

m_sort1 = cv2.sortIdx(m, cv2.SORT_EVERY_ROW) # 행렬 원소의 원본 좌표
m_sort2 = cv2.sortIdx(m, cv2.SORT_EVERY_COLUMN)
m_sort3 = np.argsort(m, axis=0) # 세로축 정렬

print("[m1] = \n%s\n" % m)
print("[m_sort1] = \n%s\n" % m_sort1)
print("[m_sort2] = \n%s\n" % m_sort2)
print("[m_sort3] = \n%s\n" % m_sort3)

[m1] = 
[[70 51 56 30 29]
 [93 48 33 83 91]
 [62 61 93 93 60]]

[m_sort1] = 
[[4 3 1 2 0]
 [2 1 3 4 0]
 [4 1 0 2 3]]

[m_sort2] = 
[[2 1 1 0 0]
 [0 0 0 1 2]
 [1 2 2 2 1]]

[m_sort3] = 
[[2 1 1 0 0]
 [0 0 0 1 2]
 [1 2 2 2 1]]

