In [2]:
import numpy as np, cv2

In [3]:
def print_rects(rects):
    print("-" * 46)# 라인 출력
    print("사각형 원소\t\t랜덤 사각형 정보\t\t  크기")
    print("-" * 46)
    for i, (x,y, w,h, a) in enumerate(rects):# 저장 데이터 출력
         print("rects[%i] = [(%3d,%3d) from (%3d,%3d)] %5d" %(i, x, y, w, h, a))
    print()

In [7]:
rands = np.zeros((5, 5), np.uint16) # 5행 5열 행렬 생성
starts = cv2.randn(rands[:, :2 ], 100, 50) # 0~4행까지 시작좌표 랜덤 생성
ends = cv2.randn(rands[:, 2:-1], 300, 50) # 5~9행까지 종료좌표 랜덤 생성

print(rands)
print(starts)
print(ends)

sizes = cv2.absdiff(starts, ends) # 시작좌표와 종료좌표간 차분 절대값
areas = sizes[:, 0] * sizes[:, 1]
rects = rands.copy()
rects[:, 2:-1] = sizes
rects[:,-1] = areas

print(sizes)
print(areas)
print(rects)

idx = cv2.sortIdx(areas, cv2.SORT_EVERY_COLUMN).flatten()
# idx = np.argsort(areas, axis=0)

print_rects(rects)
print_rects(rects[idx.astype('int')])

# ## 리스트 생성 방식
# # rects = ["[(%3d,%3d) from (%3d,%3d)]" %(p[0], p[1], s[0], s[1])
# #          for p, s in zip(starts, sizes)] # 시작좌표와 크기로 리스트 생성
# # areas = [s[0]*s[1] for s in sizes] # 넓이 계산 및 리스트에 저장
# #
# # # 정렬 후, 정렬 원소의 원본 좌표 반환
# # sort_idx = cv2.sortIdx(np.array(areas), cv2.SORT_EVERY_COLUMN)
# # sort_idx = map(int , sort_idx)
# #
# # print("-" * 46) # 라인 출력
# # print("사각형 원소\t\t랜덤 사각형 정보\t  크기")
# # print("-" * 46)
# # for i, rect, area in zip(range(5), rects, areas): # 저장 데이터 출력
# #     print("rects["+ str(i) + "] =", rect, area)
# #
# # print()
# # print("-" * 46)
# # print("사각형 원소\t\t정렬 사각형 정보\t  크기")
# # print("-" * 46)
# # for idx in sort_idx: # 정렬 데이터 출력
# #     print("rects[" + str(idx) + "] =", rects[idx], areas[idx])




[[ 94  53 414 429   0]
 [126 106 384 295   0]
 [102  51 359 201   0]
 [143 163 360 306   0]
 [ 62 128 371 228   0]]
[[ 94  53]
 [126 106]
 [102  51]
 [143 163]
 [ 62 128]]
[[414 429]
 [384 295]
 [359 201]
 [360 306]
 [371 228]]
[[320 376]
 [258 189]
 [257 150]
 [217 143]
 [309 100]]
[54784 48762 38550 31031 30900]
[[   94    53   320   376 54784]
 [  126   106   258   189 48762]
 [  102    51   257   150 38550]
 [  143   163   217   143 31031]
 [   62   128   309   100 30900]]
----------------------------------------------
사각형 원소		랜덤 사각형 정보		  크기
----------------------------------------------
rects[0] = [( 94, 53) from (320,376)] 54784
rects[1] = [(126,106) from (258,189)] 48762
rects[2] = [(102, 51) from (257,150)] 38550
rects[3] = [(143,163) from (217,143)] 31031
rects[4] = [( 62,128) from (309,100)] 30900

----------------------------------------------
사각형 원소		랜덤 사각형 정보		  크기
----------------------------------------------
rects[0] = [( 62,128) from (309,100)] 30900
rects[1] = [(143,