In [1]:
import numpy as np, cv2

In [2]:
m = np.random.randint(0,100, 15).reshape(3,5)           # 임의 난수 생성
# 행렬 원소 정렬
sort1 = cv2.sort(m, cv2.SORT_EVERY_ROW) # 행단위 오름차순
sort2 = cv2.sort(m, cv2.SORT_EVERY_COLUMN) # 열단위(세로) 오름차순
sort3 = cv2.sort(m, cv2.SORT_EVERY_ROW+cv2.SORT_DESCENDING) # 행단위(가로) 내림차순
sort4 = np.sort(m, axis=1) # 세로축 정렬
sort5 = np.sort(m, axis=0) # 가로축 정렬
sort6 = np.sort(m, axis=1)[:, ::-1] # 가로축 내림차순 정렬

titles= ['m','sort1','sort2','sort3','sort4','sort5', 'sort6']
for title in titles:
        print("[%s] = \n%s\n" %(title, eval(title)))

[m] = 
[[16 40 60 58 85]
 [17  1 62 65 59]
 [58 15 44 29  0]]

[sort1] = 
[[16 40 58 60 85]
 [ 1 17 59 62 65]
 [ 0 15 29 44 58]]

[sort2] = 
[[16  1 44 29  0]
 [17 15 60 58 59]
 [58 40 62 65 85]]

[sort3] = 
[[85 60 58 40 16]
 [65 62 59 17  1]
 [58 44 29 15  0]]

[sort4] = 
[[16 40 58 60 85]
 [ 1 17 59 62 65]
 [ 0 15 29 44 58]]

[sort5] = 
[[16  1 44 29  0]
 [17 15 60 58 59]
 [58 40 62 65 85]]

[sort6] = 
[[85 60 58 40 16]
 [65 62 59 17  1]
 [58 44 29 15  0]]

