In [3]:
import numpy as np
import cv2

In [4]:
m1 = np.full((3, 6), 10, np.uint8)# 단일 채널 생성 및 초기화
m2 = np.full((3, 6), 50, np.uint8)
m_mask = np.zeros(m1.shape, np.uint8)# 마스크 생성(m1크기로 생성)
m_mask[:,3: ] = 1# 관심 영역을 지정한 후, 1을 할당 / 모든 행을 포함하는데 열은 3부터 끝까지
print(m_mask)

m_add1 = cv2.add(m1, m2) # 행렬 덧셈
m_add2 = cv2.add(m1, m2, mask=m_mask)# 관심 영역만 덧셈 수행

print(m_add1)
print(m_add2)

# 행렬 나눗셈 수행
m_div1 = cv2.divide(m1, m2)
print(m_div1)
m1 = m1.astype(np.float32) # 형변환 - 소수 부분 보존(위에 uint8있으니까 0 나옴 -> 실수형으로 바꿔주자)
m2 = np.float32(m2) # m2.astype(np.float32)와 똑같음
m_div2 = cv2.divide(m1, m2)

titles = ['m1', 'm2', 'm_mask','m_add1','m_add2','m_div1', 'm_div2']
for title in titles:
    print("[%s] = \n%s \n" % (title, eval(title)))

[[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
[[60 60 60 60 60 60]
 [60 60 60 60 60 60]
 [60 60 60 60 60 60]]
[[ 0  0  0 60 60 60]
 [ 0  0  0 60 60 60]
 [ 0  0  0 60 60 60]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[m1] = 
[[10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]] 

[m2] = 
[[50. 50. 50. 50. 50. 50.]
 [50. 50. 50. 50. 50. 50.]
 [50. 50. 50. 50. 50. 50.]] 

[m_mask] = 
[[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]] 

[m_add1] = 
[[60 60 60 60 60 60]
 [60 60 60 60 60 60]
 [60 60 60 60 60 60]] 

[m_add2] = 
[[ 0  0  0 60 60 60]
 [ 0  0  0 60 60 60]
 [ 0  0  0 60 60 60]] 

[m_div1] = 
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]] 

[m_div2] = 
[[0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2]] 

