In [1]:
import numpy as np, cv2

In [2]:
# numpy array 생성 예시
v1 = np.array([1, 2, 3], np.float32)          # 1차원 리스트로 생성- 행벡터
v2 = np.array([[1], [2], [3]], np.float32)      # 2차원 리스트로(3행, 1열) - 행벡터
v3 = np.array([[1, 2, 3]], np.float32)        	# 2차원 리스트로(1행, 3열) - 일반 행렬

# OpenCV 산술 연산 함수는 numpy array만 가능함
v1_exp = cv2.exp(v1) # 벡터에 대한 지수 계산
v2_exp = cv2.exp(v2) # 행렬에 대한 지수 계산
v3_exp = cv2.exp(v3) # 행렬에 대한 지수 계산
v_log = cv2.log(v1) # 로그 계산
m_sqrt= cv2.sqrt(v2) # 제곱근 계산
m_pow = cv2.pow(v3, 3) # 3의 거듭제곱 계산

# 결과 출력
print("[v1] 형태: %s 원소: %s" % ( v1.shape, v1))
print("[v2] 형태: %s 원소:\n%s" % ( v2.shape, v2))
print("[v3] 형태: %s 원소: %s" % ( v3.shape, v3))
print()

# 행렬 정보 출력 - OpenCV 결과는 행렬로 반환됨 - 행벡터는 엘벡터로 반환됨
print("[v1_exp] 자료형: %s 형태: %s" % ( type(v1_exp), v1_exp.shape))  # 행벡터 인수의 결과
print("[v2_exp] 자료형: %s 형태: %s" % ( type(v2_exp), v2_exp.shape))  # 행벡터 인수의 결과
print("[v3_exp] 자료형: %s 형태: %s" % ( type(v3_exp), v3_exp.shape))  # 행벡터 인수의 결과
print()

# 열벡터를 하나의 행에 출력하는 예시 - 행벡터로 변환
print("[log] =", v_log.T)
print("[sqrt] =", np.ravel(m_sqrt))         
print("[pow] =", m_pow.flatten())

[v1] 형태: (3,) 원소: [1. 2. 3.]
[v2] 형태: (3, 1) 원소:
[[1.]
 [2.]
 [3.]]
[v3] 형태: (1, 3) 원소: [[1. 2. 3.]]

[v1_exp] 자료형: <class 'numpy.ndarray'> 형태: (3, 1)
[v2_exp] 자료형: <class 'numpy.ndarray'> 형태: (3, 1)
[v3_exp] 자료형: <class 'numpy.ndarray'> 형태: (1, 3)

[log] = [[0.        0.6931472 1.0986123]]
[sqrt] = [1.        1.4142135 1.7320508]
[pow] = [ 1.  8. 27.]


In [15]:
# 이런 shape의 넘파이 배열이 있을 때
x = np.array([[ 0, 1, 2, 3],
        [ 4, 5, 6, 7],
        [ 8, 9, 10, 11]])


# 옵션 'C'
x1 = np.ravel(x, order='C') # default 값
print(x1)

z = cv2.pow(x, 1)                          # 3의 거듭제곱 계산
x2 = z.flatten() # default 값
print(x2)
# # Out: array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

# # 옵션 'K'
# np.ravel(x, order='K')
# ...:
# # Out: array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

# # 옵션 'F'
# np.ravel(x, order='F')
# ...:
# # Out: array([ 0, 4, 8, 1, 5, 9, 2, 6, 10, 3, 7, 11])
# # 3차원 배열일 때 사용 예시

# # 이런 배열이 있을 때
# x = array([[[ 0, 1],
#          [ 2, 3],
#          [ 4, 5]],

#         [[ 6, 7],
#          [ 8, 9],
#          [10, 11]]])

# # 옵션 'C'
# np.ravel(x, order='C')
# ...:
# # Out: array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])


# # x 배열의 축이 바뀌었을 때
# x = array([[[ 0, 2, 4],
#          [ 1, 3, 5]],

#         [[ 6, 8, 10],
#          [ 7, 9, 11]]]) # x = x.swapaxes(1, 2)

# # 옵션 'K'
# np.ravel(x, order='K')
# ...:
# # Out: array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
