In [2]:
import cv2
import numpy as np

In [3]:
L = 16

In [4]:
# 1. image : using “np.array([[ ]])”
image = np.array([[0,0,10,10,10],
                  [10,11,11,11,11],
                  [12,12,12,12,13],
                  [13,13,13,13,13]], dtype=np.uint8)
h,w = image.shape

# 2. histogram : using “cv2.calcHist”
hist = cv2.calcHist(images = [image], channels=[0], mask=None, histSize =[L], ranges=[0,L-1])

# 3. cumulative sum vector : using “np.cumsum”
cdf = np.cumsum(hist)

# 4. normalization(cdf_norm): divide by “max of cdf”
cdf_normalized = cdf / np.max(cdf)

# 5. mapping table : using “np.round”
table = np.round(cdf_normalized * L)

# 6. mapping(output) : using “nested loop”
output = np.zeros((h,w))
for i in range(0,h):
    for j in range(0,w):
        output[i,j] = table[image[i,j]]
        output = np.uint8(output)
                               
# 7. check the result : using “print"
print(output)

[[ 2  2  5  5  5]
 [ 5  8  8  8  8]
 [11 11 11 11 16]
 [16 16 16 16 16]]
